#
# Never have I thought this day would come, but here I go, my first python
# program. And it deals with pickles. damn!
#

import time
import zmq
import mammogram_header_pb2 as mammo
import mammogram_result_pb2 as mammo_result

import numpy as np
import matplotlib.pylab as plt
from matplotlib import cm

# only needed for the test files during the development
import pickle as pkl
import sys  

f = open('C:/Users/twitzel/Downloads/plugin_examples2/plugin_examples2/heatmaps_DDSM/patient-491_LMLO.pkl','rb')

# Here we have the first wrinkle, python3.5, which I'm using cannot read pickle
# files that were generated by python 2.7. Setting the encoding to 'bytes' will
# get around the problem. Apparently 'latin-1' is a winner as well
heatmap = pkl.load(f,fix_imports=True,encoding='bytes')

# See what we got
plt.imshow(heatmap, cmap='gray')
plt.show()
